---
- name: Install MariaDB server
  yum:
    name: mariadb-server
    state: present

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Set root password (Amazon Linux only if MySQL 5.x)
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: true
  when: ansible_facts['distribution'] == "Amazon"